// src/entities/create-plan-loader/ui/CreatePlanLoader.tsx
import CountUp from 'react-countup';

import './create-plan-loader.css';

export function CreatePlanLoader() {
  return (
    <div className="relative">
      <svg
        width="150"
        height="150"
        viewBox="0 0 150 150"
        className="create-plan-loader"
      >
        <circle className="create-plan-loader__background"></circle>
        <circle className="create-plan-loader__loader"></circle>
      </svg>

      <span className="flex justify-center items-center text-3xl font-bold absolute inset-0">
        <CountUp className="min-w-10" duration={10} end={100} />
        <span>%</span>
      </span>
    </div>
  );
}

// src/entities/create-plan-loader/ui/CreatePlanLoader.vue
<script setup lang="ts">
  import gsap from 'gsap';
  import { onMounted, reactive } from 'vue';

  import './create-plan-loader.css';

  const props = withDefaults(
    defineProps<{
      animationDuration?: number;
    }>(),
    {
      animationDuration: 9,
    }
  );

  const tweened = reactive({
    number: 0,
  });

  onMounted(() => {
    gsap.to(tweened, { duration: props.animationDuration, number: 100 });
  });
</script>

<template>
  <div class="relative w-fit">
    <svg
      class="create-plan-loader"
      :style="{ '--animation-duration': `${animationDuration}s` }"
      width="150"
      height="150"
      viewBox="0 0 150 150"
    >
      <circle class="create-plan-loader__background" r="100%"></circle>
      <circle class="create-plan-loader__loader" r="100%"></circle>
    </svg>

    <span class="absolute inset-0 flex items-center justify-center text-3xl font-bold">
      <span>{{ tweened.number.toFixed(0) }}</span>
      <span>%</span>
    </span>
  </div>
</template>
