// src/entities/legal-links/ui/LegalLinks.vue
<script setup lang="ts">
  import { RouterLink } from 'vue-router';

  const PAGE_SLUGS = {
    privacy: {
      name: 'LegalPage',
      params: {
        slug: 'privacy',
      },
    },
    terms: {
      name: 'LegalPage',
      params: {
        slug: 'terms',
      },
    },
  };
</script>

<template>
  <p class="text-purple-text-primary group text-center text-xs opacity-60">
    By choosing your age, you agree with
    <RouterLink :to="PAGE_SLUGS.terms" class="underline"> Terms and Conditions, </RouterLink>
    <RouterLink :to="PAGE_SLUGS.privacy" class="underline"> Privacy Policy </RouterLink>
  </p>
</template>

// src/entities/legal-links/ui/LegalLinks.tsx
import { Link } from 'react-router-dom';
import { ROUTES } from '~shared/config';

const PAGE_SLUGS = {
  privacy: ROUTES.LEGAL.path('privacy'),
  terms: ROUTES.LEGAL.path('terms'),
};

export function LegalLinks() {
  return (
    <p className="text-purple-text-primary group opacity-60 text-center text-xs">
      By choosing your age, you agree with{' '}
      <Link to={PAGE_SLUGS.terms} className="underline">
        Terms and Conditions
      </Link>
      ,{' '}
      <Link to={PAGE_SLUGS.privacy} className="underline">
        Privacy Policy
      </Link>
    </p>
  );
}
