// src/widgets/quiz-question/ui/QuizWithRadioAnswers.vue
<script setup lang="ts">
  import { AnswerRadio } from '~entities/answer';
  import { type Funnel } from '~entities/funnel';

  defineProps<{
    content: Funnel['QuizQuestion'];
  }>();

  const emit = defineEmits<{
    (e: 'onSelected', answer: Array<Funnel['QuizAnswer']['slug']>): void;
  }>();
</script>

<template>
  <div class="mt-6 w-full pb-6">
    <ul class="flex flex-col space-y-3">
      <li v-for="answer in content.answers" :key="answer.slug">
        <AnswerRadio :answer="answer" @onSelected="emit('onSelected', [answer.slug])" />
      </li>
    </ul>
  </div>
</template>

// src/widgets/quiz-question/ui/QuizWithRadioAnswers.tsx
import { AnswerRadio } from '~entities/answer';
import { type Funnel } from '~entities/funnel';

export function QuizWithRadioAnswers(props: {
  content: Funnel['QuizQuestion'];
  events: {
    onSelected: () => void;
  };
}) {
  function onSelect(answer: Funnel['QuizAnswer']) {
    console.log('radio', answer);

    props.events.onSelected();
  }

  return (
    <div className="mt-6 pb-6">
      <ul className="flex flex-col space-y-3">
        {props.content.answers.map(answer => (
          <li key={answer.slug}>
            <AnswerRadio answer={answer} events={{ onSelect }} />
          </li>
        ))}
      </ul>
    </div>
  );
}
