// src/widgets/quiz-question/ui/QuizQuestionWidget.vue
<script setup lang="ts">
  import { UiHeadline } from '~shared/ui';

  import { type Funnel, QUIZ_ANSWER_TYPES, useFunnelStore } from '~entities/funnel';

  import QuizWithButtonsAnswers from './QuizWithButtonsAnswers.vue';
  import QuizWithMultipleAnswers from './QuizWithMultipleAnswers.vue';
  import QuizWithRadioAnswers from './QuizWithRadioAnswers.vue';

  const props = defineProps<{
    content: Funnel['QuizQuestion'];
  }>();

  const emit = defineEmits<{
    (e: 'onContinue'): void;
  }>();

  const funnelStore = useFunnelStore();

  function onSelected(answers: Array<Funnel['QuizAnswer']['slug']>) {
    funnelStore.setSelectedQuizDataBySlug(props.content.slug, answers);

    emit('onContinue');
  }
</script>

<template>
  <div class="flex w-full flex-1 flex-col">
    <UiHeadline
      :title="content.title"
      :subtitle="content.subtitle"
      :description="content.description"
    />

    <QuizWithRadioAnswers
      v-if="content.answerType === QUIZ_ANSWER_TYPES.radio"
      :content="content"
      @onSelected="onSelected"
    />

    <QuizWithMultipleAnswers
      v-if="content.answerType === QUIZ_ANSWER_TYPES.multiple"
      :content="content"
      @onSelected="onSelected"
    />

    <QuizWithButtonsAnswers
      v-if="content.answerType === QUIZ_ANSWER_TYPES.buttons"
      :content="content"
      @onSelected="onSelected"
    />
  </div>
</template>

// src/widgets/quiz-question/ui/QuizQuestionWidget.tsx
import { type Funnel, QUIZ_ANSWER_TYPES } from '~entities/funnel';
import { UiHeadline } from '~shared/ui';

import { QuizWithButtonsAnswers } from './QuizWithButtonsAnswers';
import { QuizWithMultipleAnswers } from './QuizWithMultipleAnswers';
import { QuizWithRadioAnswers } from './QuizWithRadioAnswers';

function getQuizContentByType(props: {
  content: Funnel['QuizQuestion'];
  events: {
    onGoToNextPage: () => void;
  };
}) {
  switch (props.content.answerType) {
    case QUIZ_ANSWER_TYPES.radio:
      return (
        <QuizWithRadioAnswers
          content={props.content}
          events={{ onSelected: props.events.onGoToNextPage }}
        />
      );
    case QUIZ_ANSWER_TYPES.multiple:
      return (
        <QuizWithMultipleAnswers
          content={props.content}
          events={{
            onSelected: props.events.onGoToNextPage,
          }}
        />
      );
    case QUIZ_ANSWER_TYPES.buttons:
      return (
        <QuizWithButtonsAnswers
          content={props.content}
          events={{ onSelected: props.events.onGoToNextPage }}
        />
      );
    default:
      return null;
  }
}

export function QuizQuestionWidget(props: {
  content: Funnel['QuizQuestion'];
  events: {
    onGoToNextPage: () => void;
  };
}) {
  return (
    <section className="flex flex-col pt-5 pb-6 px-4 overflow-auto">
      <UiHeadline
        title={props.content.title}
        subtitle={props.content.subtitle}
        description={props.content.description}
      />

      {getQuizContentByType({
        content: props.content,
        events: {
          onGoToNextPage: props.events.onGoToNextPage,
        },
      })}
    </section>
  );
}
