// src/entities/answer/ui/AnswerRadio.tsx
import type { Funnel } from '~entities/funnel';

export function AnswerRadio(props: {
  answer: Funnel['QuizAnswer'];
  events: {
    onSelect: (answer: Funnel['QuizAnswer']) => void;
  };
}) {
  return (
    <button
      type="button"
      className="rounded-lg min-h-16 border border-slate-200 w-full flex items-center text-left space-x-3 pl-3 pr-4 py-4 duration-200 active:border-purple-primary active:bg-indigo-50"
      onClick={() => props.events.onSelect(props.answer)}
    >
      <span className="text-xl">{props.answer.icon}</span>
      <span className="text-sm font-semibold">{props.answer.title}</span>
    </button>
  );
}

// src/entities/answer/ui/AnswerRadio.vue
<script setup lang="ts">
  import type { Funnel } from '~entities/funnel';

  defineProps<{
    answer: Funnel['QuizAnswer'];
    isSelected?: boolean;
  }>();

  const emit = defineEmits<{
    (e: 'onSelected', answer: Funnel['QuizAnswer']): void;
  }>();
</script>

<template>
  <button
    type="button"
    class="flex min-h-16 w-full touch-manipulation items-center space-x-3 rounded-lg border py-4 pr-4 pl-3 text-left duration-200"
    :class="
      isSelected
        ? 'border-purple-primary bg-indigo-50'
        : 'active:border-purple-primary border-slate-200 active:bg-indigo-50'
    "
    @click="emit('onSelected', answer)"
  >
    <span class="text-xl">{{ answer.icon }}</span>
    <span class="text-sm font-semibold">{{ answer.title }}</span>
  </button>
</template>
