// src/entities/answer/ui/AnswerMultiple.vue
<script setup lang="ts">
  import type { Funnel } from '~entities/funnel';

  defineProps<{
    answer: Funnel['QuizAnswer'];
    isSelected: boolean;
  }>();

  const emit = defineEmits<{
    (e: 'onSelected', answer: Funnel['QuizAnswer']): void;
  }>();
</script>

<template>
  <button
    type="button"
    class="group active:border-purple-primary flex min-h-16 w-full touch-manipulation items-center justify-between space-x-3 rounded-lg border py-4 pr-4 pl-3 text-left duration-200 active:bg-indigo-50"
    :class="isSelected ? 'border-purple-primary bg-indigo-50' : 'border-slate-200'"
    @click="emit('onSelected', answer)"
  >
    <span class="flex flex-1 items-center space-x-3">
      <span class="text-xl">{{ answer.icon }}</span>
      <span class="text-sm font-semibold">{{ answer.title }}</span>
    </span>

    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="20"
      height="20"
      fill="none"
      class="duration-200 group-active:opacity-100"
      :class="isSelected ? 'opacity-100' : 'opacity-0'"
    >
      <rect width="20" height="20" fill="#5653FE" rx="6" />
      <path
        fill="#fff"
        fill-rule="evenodd"
        d="M15.374 5.793a1 1 0 0 1 0 1.414l-6.416 6.417a1 1 0 0 1-1.414 0l-2.917-2.917A1 1 0 1 1 6.04 9.293l2.21 2.21 5.71-5.71a1 1 0 0 1 1.413 0Z"
        clip-rule="evenodd"
      />
    </svg>
  </button>
</template>

// src/entities/answer/ui/AnswerMultiple.tsx
import classNames from 'classnames';
import type { Funnel } from '~entities/funnel';

export function AnswerMultiple(props: {
  answer: Funnel['QuizAnswer'];
  events: {
    onSelect: (answer: Funnel['QuizAnswer']) => void;
  };
}) {
  const isSelected = false; // TODO: add zustand to implement reactive activation

  return (
    <button
      type="button"
      className={classNames(
        'group rounded-lg min-h-16 border  w-full flex justify-between items-center text-left space-x-3 pl-3 pr-4 py-4 duration-200 active:border-purple-primary active:bg-indigo-50',
        isSelected ? 'border-purple-primary bg-indigo-50' : 'border-slate-200'
      )}
      onClick={() => props.events.onSelect(props.answer)}
    >
      <span className="flex items-center flex-1 space-x-3">
        <span className="text-xl">{props.answer.icon}</span>
        <span className="text-sm font-semibold">{props.answer.title}</span>
      </span>

      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        fill="none"
        className={classNames(
          'duration-200 group-active:opacity-100',
          isSelected ? 'opacity-100' : 'opacity-0'
        )}
      >
        <rect width="20" height="20" fill="#5653FE" rx="6" />
        <path
          fill="#fff"
          fillRule="evenodd"
          d="M15.374 5.793a1 1 0 0 1 0 1.414l-6.416 6.417a1 1 0 0 1-1.414 0l-2.917-2.917A1 1 0 1 1 6.04 9.293l2.21 2.21 5.71-5.71a1 1 0 0 1 1.413 0Z"
          clipRule="evenodd"
        />
      </svg>
    </button>
  );
}
