// src/entities/answer/ui/AnswerButton.tsx
import type { Funnel } from '~entities/funnel';

export function AnswerButton(props: {
  answer: Funnel['QuizAnswer'];
  events: {
    onSelect: (answer: Funnel['QuizAnswer']) => void;
  };
}) {
  return (
    <button
      type="button"
      className="rounded-lg aspect-square w-full border border-slate-200 text-center duration-200 active:border-purple-primary active:bg-indigo-50"
      onClick={() => props.events.onSelect(props.answer)}
    >
      {props.answer.icon}
    </button>
  );
}

// src/entities/answer/ui/AnswerButton.vue
<script setup lang="ts">
  import type { Funnel } from '~entities/funnel';

  defineProps<{
    answer: Funnel['QuizAnswer'];
    isSelected?: boolean;
  }>();

  const emit = defineEmits<{
    (e: 'onSelected', answer: Funnel['QuizAnswer']): void;
  }>();
</script>

<template>
  <button
    type="button"
    class="aspect-square w-full touch-manipulation rounded-lg border text-center duration-200"
    :class="
      isSelected
        ? 'border-purple-primary bg-indigo-50'
        : 'active:border-purple-primary border-slate-200 active:bg-indigo-50'
    "
    @click="emit('onSelected', answer)"
  >
    {{ answer.icon }}
  </button>
</template>
