// src/shared/ui/button/ui/UiButton.vue
<script setup lang="ts">
  defineProps<{
    title: string;
  }>();

  const emit = defineEmits<{
    (e: 'onClick'): void;
  }>();
</script>

<template>
  <button
    type="button"
    class="bg-purple-primary h-12 w-full touch-manipulation rounded-lg text-white duration-200 active:opacity-85"
    @click="emit('onClick')"
  >
    {{ title }}
  </button>
</template>

// src/shared/ui/button/ui/UiButton.tsx
export function UiButton(props: {
  title: string;
  events: {
    onClick: () => void;
  };
}) {
  return (
    <button
      type="button"
      className="bg-purple-primary text-white h-12 w-full rounded-lg active:opacity-85 duration-200"
      onClick={() => props.events.onClick()}
    >
      {props.title}
    </button>
  );
}
