// src/shared/ui/headline/ui/UiHeadline.vue
<script setup lang="ts">
  defineProps<{
    title: string;
    subtitle?: string;
    description?: string;
  }>();
</script>

<template>
  <div class="text-center text-pretty">
    <h1 v-html="title" class="text-xl font-semibold"></h1>
    <h2 v-if="subtitle" v-html="subtitle" class="mt-4 text-xs"></h2>
    <p v-if="description" v-html="description" class="mt-3 text-xs uppercase"></p>
  </div>
</template>

// src/shared/ui/headline/ui/UiHeadline.tsx
import classNames from 'classnames';

export function UiHeadline(props: {
  title: string;
  subtitle?: string;
  description?: string;
  className?: string;
}) {
  return (
    <div className={classNames('text-center text-pretty', props.className)}>
      <h1
        dangerouslySetInnerHTML={{ __html: props.title }}
        className="text-xl font-semibold"
      ></h1>
      {props.subtitle && (
        <h2
          dangerouslySetInnerHTML={{ __html: props.subtitle }}
          className="mt-4 text-xs"
        ></h2>
      )}
      {props.description && (
        <p
          dangerouslySetInnerHTML={{ __html: props.description }}
          className="text-xs mt-3 uppercase"
        ></p>
      )}
    </div>
  );
}
