// src/pages/legal/ui/LegalPageShimmer.vue
<template>
  <div class="px-4 pt-6">
    <div class="space-y-2">
      <div class="h-5 w-6/12 animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-full animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-10/12 animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-11/12 animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-8/12 animate-pulse rounded bg-gray-100"></div>
    </div>

    <div class="mt-6 space-y-2">
      <div class="h-5 w-full animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-10/12 animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-11/12 animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-10/12 animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-8/12 animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-10/12 animate-pulse rounded bg-gray-100"></div>
    </div>

    <div class="mt-6 space-y-2">
      <div class="h-5 w-full animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-10/12 animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-11/12 animate-pulse rounded bg-gray-100"></div>
      <div class="h-5 w-8/12 animate-pulse rounded bg-gray-100"></div>
    </div>
  </div>
</template>

// src/pages/legal/ui/LegalPageShimmer.tsx
export function LegalPageShimmer() {
  return (
    <div className="px-4 pt-6">
      <div className="space-y-2">
        <div className="h-5 rounded w-6/12 bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-full bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-10/12 bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-11/12 bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-8/12 bg-gray-100 animate-pulse"></div>
      </div>

      <div className="mt-6 space-y-2">
        <div className="h-5 rounded w-full bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-10/12 bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-11/12 bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-10/12 bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-8/12 bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-10/12 bg-gray-100 animate-pulse"></div>
      </div>

      <div className="mt-6 space-y-2">
        <div className="h-5 rounded w-full bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-10/12 bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-11/12 bg-gray-100 animate-pulse"></div>
        <div className="h-5 rounded w-8/12 bg-gray-100 animate-pulse"></div>
      </div>
    </div>
  );
}
