// src/shared/layout/base-layout/ui/BaseLayout.tsx
import type React from 'react';
import { AppToolbar } from '~entities/toolbar';

interface BaseLayoutProps {
  children: React.ReactNode;
  withProgressBar?: boolean;
  progress?: number;
  isCanGoBack?: boolean;
  events?: {
    onGoBack?: () => void;
  };
}

export function BaseLayout(props: BaseLayoutProps) {
  return (
    <main className="text-purple-text-primary vh-full overflow-hidden grid grid-rows-[auto_1fr_auto] max-w-[500px] mx-auto">
      <header>
        <AppToolbar
          withProgressBar={props?.withProgressBar}
          isCanGoBack={props?.isCanGoBack}
          progress={props.progress}
          events={props?.events}
        />
      </header>

      {props.children}
    </main>
  );
}

// src/shared/layout/base-layout/ui/BaseLayout.vue
<script setup lang="ts">
  import { AppToolbar } from '~entities/toolbar';

  defineProps({
    withProgressBar: {
      type: Boolean,
      default: false,
    },
    progress: {
      type: Number,
      default: 0,
    },
    isCanGoBack: {
      type: Boolean,
      default: false,
    },
  });

  const emit = defineEmits<{
    (e: 'onGoBack'): void;
  }>();

  function onGoBack() {
    emit('onGoBack');
  }
</script>

<template>
  <main
    class="text-purple-text-primary vh-full mx-auto grid max-w-[500px] grid-rows-[auto_1fr_auto] overflow-hidden"
  >
    <header>
      <AppToolbar
        :with-progress-bar="withProgressBar"
        :is-can-go-back="isCanGoBack"
        :progress="progress"
        @onGoBack="onGoBack"
      />
    </header>

    <slot></slot>
  </main>
</template>
